### ISSUE TITLE
Version for windows?

### ISSUE THREAD

**Issue by Adrianogba** [shobhitpuri/git-refresh#3]
This doesn't appear to work on windows. Can you create an example of this commands to run on windows?

**Comment by Ryanman** [comment]
This does work on Win10 as of 11/20/2020, if you put these files in your path (something like ` C:\Program Files\Git\cmd ` ) with Git for Windows installed

**Comment by shobhitpuri** [comment]
Thanks @Ryanman for replying on the issue. 👍  
@Adrianogba please see if the above suggestion fixes your issue. If not feel free to reopen the issue.
